[package]
org = "user"
name = "service"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

[[platforms.local.modules]]
org = "ballerinax"
name = "mongodb"
version = "7.0.2"  # Specify the version compatible with your Ballerina version
